[project]

fullname = "Corpus der Entscheidungen des Bundesverwaltungsgerichts"
shortname = "CE-BVerwG"
author = "Seán Fobbe"



[license]

data = "Creative Commons Zero 1.0 Universal"
code = "MIT-0"



[doi] # Digital Object Identifier

data.concept = "10.5281/zenodo.3911067" # do not change
data.version = "10.5281/zenodo.7749683" # checked

software.concept = "10.5281/zenodo.4625134" # do not change
software.version = "10.5281/zenodo.7749684" # checked

personendaten = "10.5281/zenodo.4568682" # checked
aktenzeichen = "10.5281/zenodo.4569564" # checked




[debug]

toggle = true   # Ob Debugging aktiv ist; Möglichkeiten sind "true" oder "false"
files = 100 # Die Anzahl der Dateien, die testweise heruntergeladen werden soll.

cleanrun = false # Löscht vor jedem Run alle gespeicherten Zwischen- und Endergebnisse (Hinweis: ist unabhängig von debug.toggle, aber idR für Debugging nützlich)



[annotate] # Linguistische Annotationen

# Wenn dieser Modus aktiviert ist wird  mittels spacyr eine zusätzliche Variante des Datensatzes mit umfangreichen linguistischen Annotationen berechnet. Dieser Modus ist sehr rechenintensiv! Kann mit Debugging kombiniert werden. Aktuell nicht verfügbar, weil unlösebare Probleme mit spacy auftreten.

toggle = false




[cores]

max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
number = 8   # Die Anzahl Rechenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht



[parallel]

extractPDF = true
lingsummarize = true
multihashes = true



[download]

max = 28000    # Maximale Anzahl an heruntergeladenen Entscheidungen
timeout = 600	  # Timeout für Downloads



[quanteda]

tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



[fig] #  Knitr

format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
dpi = 300     	 	# Auflösung für Diagramme
align = "center"    	# Ausrichtung von Diagrammen im Compilation Report
