#=== Project ===

project.fullname = "Corpus der Entscheidungen des Bundesverwaltungsgerichts"
project.shortname = "CE-BVerwG"
project.author = "Seán Fobbe"



#=== License ===

license.data = "Creative Commons Zero 1.0 Universal"
license.code = "MIT-0"



#=== Digital Object Identifier (DOI) ===

doi.data.concept = "10.5281/zenodo.3911067" # do not change
doi.data.version = "10.5281/zenodo.6960173" # checked

doi.software.concept = "10.5281/zenodo.4625134" # do not change
doi.software.version = "10.5281/zenodo.6960176" # checked

doi.personendaten = "10.5281/zenodo.4568682" # checked
doi.aktenzeichen = "10.5281/zenodo.4569564" # checked


#=== Modus: Debugging ===

debug.toggle = true   # Ob Debugging aktiv ist; Möglichkeiten sind "true" oder "false"
debug.files = 100 # Die Anzahl der Dateien, die testweise heruntergeladen werden soll.


#=== Modus: Linguistische Annotationen ===
# Wenn dieser Modus aktiviert ist wird  mittels spacyr eine zusätzliche Variante des Datensatzes mit umfangreichen linguistischen Annotationen berechnet. Dieser Modus ist sehr rechenintensiv! Kann mit Debugging kombiniert werden.

annotate.toggle = true



#=== Parallelization ===

cores.max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
cores.number = 8   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht


parallel.extractPDF = true
parallel.lingsummarize = true
parallel.multihashes = true



#=== Download ===

download.timeout = 600	  # Timeout für Downloads
download.max = 26000    # Maximale Anzahl an heruntergeladenen Entscheidungen


#=== Quanteda ===
quanteda.tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



#=== Knitr ===

fig.format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
fig.dpi = 300     	 	# Auflösung für Diagramme
fig.align = "center"    	# Ausrichtung von Diagrammen im Compilation Report
